### ISSUE TITLE
[Feature] Add uninstall.cmd

### ISSUE THREAD

**Issue by zuilintan** [yakunins/language-indicator#2]
First of all, brother, you are my superman!
This function is a gospel for the big screen office!
I often use the deleted key to waste time because of the characters in the wrong language.

By the way, I found that our project has no function to uninstall it,
Maybe you can consider adding it to make the software more complete.

**Comment by yakunins** [comment]
Good point → https://github.com/yakunins/language-indicator/commit/2437d6c67ccd548b7d7e3a069516b5a98fb2e1ab
