### ISSUE TITLE
Real-time refreshing of the mark consumes too much CPU. How to adjust the refresh interval?

### ISSUE THREAD

**Issue by InMirrors** [yakunins/language-indicator#4]
Thank you for your work, it has been very helpful. However, when I use the arrow keys to move the caret, it consumes too much CPU. How can I modify the source code to adjust the refresh interval and reduce CPU usage?

**Comment by yakunins** [comment]
Hello, @InMirrors 

> it consumes too much CPU

This is quite intresting. I watched `language-indicator.exe` and never seen it consumes more than 0.6% of my CPU.
I tested it in Sublime Text 3 and VS Code...
Would you please provide some info about CPU itself, application and the amount that was taken off?
