### ISSUE TITLE
Feature Request about IME

### ISSUE THREAD

**Issue by nuntavits** [yakunins/language-indicator#5]
Hi yakunins,

First of all, let me thank you for creating this program. It's really helpful. If possible, I would like to request so the program work with IME state. 

Right now, I have two input-languages, Thai and Microsoft IME (for inputting English and Japanese). The script work great, meaning the cursor and caret change from regular one (Microsoft IME) to the red dot (Thai) and vice versa.

As in Microsoft IME, I can change from inputting English and Japanese, it would be great if the program changes the cursor and the caret as well depend on the English/Japanese mode in Microsoft IME. For example, normal cursor/caret when in Microsoft IME with English mode, red cursor/caret in Japanese mode, yellow one in Thai mode.

There seem to have a function to check the state if the IME is on (Japanese input) or off (English input), but I have no idea on how to incorporate that to your program.
https://github.com/kdr-s/ime.ahk-v2/blob/master/IME.ahk

Again, I will be very grateful if you could update the program to work with the above scenario, but if not, the program works great and I'm really appreciated for the program. By the way, I think this is also the same with what superuser7777 in another thread.

Best regards,
Nuntavit

PS. I also include the screenshot to help understanding better.
![input language](https://github.com/user-attachments/assets/05a790d1-d23d-4d4c-8a7d-d349318ce835)
![microsoftIME_englishMode](https://github.com/user-attachments/assets/22b48c67-6241-4ee4-b3f8-40e29ba12bff)
![microsoftIME_japaneseMode](https://github.com/user-attachments/assets/bf21b9f6-6eaf-4961-a592-9f740e062387)

**Comment by nuntavits** [comment]
Considering this closed. I'm able to modify the script to work as expected. Thank you so much for the script. I've been looking for something like this for so long.

**Comment by yakunins** [comment]
@nuntavits 
BTW here's the piece of code that populates array of languages:
https://github.com/yakunins/language-indicator/blob/master/lib/GetInputLocaleId.ahk
