### ISSUE TITLE
compatible language: Chinese

### ISSUE THREAD

**Issue by ycy314** [yakunins/language-indicator#7]
Thank you so much for your solution, it's something I've been looking for, a very elegant solution,
But I find it doesn't seem to work on Chinese. Have you tried Chinese?

In the picture below, the first chapter shows the Chinese input status, and the second chapter shows the English input status. The ICONS displayed in two different languages are the same, which is not normal。

![1](https://github.com/user-attachments/assets/42b07877-3f06-42b1-8be2-48ba4afdfd38)
![2](https://github.com/user-attachments/assets/bd2b6037-708c-4f5b-9f63-1951be610cd1)

**Comment by yakunins** [comment]
Err... Seems like you are using Google Input Tools. And they **do not switch** windows-native input locale, so my solution cannot recognize language. Sorry, you have to add language natively, see https://www.google.com/search?q=windows+add+input+language
